name: learn-github-actions # optional - name of workflow
on: [push] # trigger - push event in this case.
jobs: # list of jobs 
  check-bats-version: # job named check-bats-version
    runs-on: ubuntu-latest # runner agent (ubuntu, in this case). Similar to creating fresh VM per execution. Can also be self hosted
    steps: # list of steps for job named check-bats-version
      - uses: actions/checkout@v3 # this step runs v3 of actions/checkout. Will pull down all files in this repo on runner
      - uses: actions/setup-node@v3 # install nodejs and npm on runner. version specified below
        with:
          node-version: '14' # nodejs version
      - run: npm install -g bats # after nodejs is installed run this on bash shell to install bats using npm 
      - run: bats -v # run bats command # after bats is installed check version
